# file: roles/solr/meta/main.yml
---
galaxy_info:
  author: Maksud Sharif
  description: Apache Solr for ArkCase.
  company: "Armedia LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.2
  platforms:
    - name: EL
      versions:
      - 7
  galaxy_tags:
    - arkcase
    - solr
    - search
    - lucene
    - apache

dependencies: []